DEFAULT_INTERVAL = (0, 0)
AUTH_TIMEOUT = 3
EXPORT_BTN_TIMEOUT = 3
EXPORT_BTN_CLICK_TIMEOUT = 2
EXPORT_INNER_BTN_CLICK_TIMEOUT = 2
RADIO_BTNS_TIMEOUT = 3
ERROR_PIC_FILENAME = 'error.png'
URLS_DELIMITER = ', '
